Add smbios tables details
ARM-software/ebbr pull request #108
Opened 2023-09-08 09:47 UTC by vstehle

Start easy and just add details about the SMBIOS tables and structures, with a reference to the SMBIOS specification v3.7.0.
Should we remove the conditional and require SMBIOS?

2023-09-08 12:01 UTC, nullr0ute commented
> Should we remove the conditional and require SMBIOS?

Yes, I think we should. A lot of support tools use SMBIOS to provide information to users in a GUI/TUI and collect information for support cases. By propagating that information the existing versions of these tools will just function as expected and we don't have to try and boil the ocean to get everything updated to support other mechanisms. It's also a requirement of ServerReady so it allows alignment across all SystemReady certs.

2023-09-08 12:04 UTC, nullr0ute commented
Example tool is [sosreport](https://github.com/sosreport/sos) and an example issue with a [GUI management tool](https://github.com/cockpit-project/cockpit/issues/16972)

2023-09-27 13:29 UTC, vstehle commented
Rebased.

2023-09-27 15:36 UTC, nullr0ute commented
Should we have somewhere in the spec around suggesting/requiring SMBIOS tables to be presented and complete/accurate?

2023-10-13 11:14 UTC, nullr0ute commented
Also this is useful:
https://developer.arm.com/documentation/102677/0100/SMBIOS-requirements

2023-10-13 12:24 UTC, samerhaj commented
One solution is for EBBR to reference specific items from [Base Boot Requirements (BBR) specification](https://developer.arm.com/documentation/den0044/), section 9 - SMBIOS REQUIREMENTS.

It is also possible to do it the other way around (or both ways), where the BBR specification (which already references EBBR spec, when defining the EBBR receipe) can detail the SMBIOS requirements for such systems. I can help with adding that language (or cross-reference) in BBR when needed.

2024-01-10 11:10 UTC, vstehle commented
Rebased.

2024-03-12 13:30 UTC, vstehle commented
Moving to draft after [call of 11 Mar](https://github.com/ARM-software/ebbr/wiki/EBBR-Notes-2024.03.11).

2024-03-12 14:09 UTC, vstehle commented
Respun:
- Only "strongly recommend" SMBIOS, and when implemented require structures
- Remove Type 32 from table of required structures
- Warn that SMBIOS will be required in the future
- Add a note to clarify that firmware can provide more than what is required

2024-06-14 09:02 UTC, vstehle commented
Trim down even more: only recommend SMBIOS and do not require any specific structure or table.

2024-06-17 14:05 UTC, xypron requested changes

2024-06-17 14:05 UTC, xypron commented on source/chapter2-uefi.rst
> +It is strongly recommended that firmware provides SMBIOS tables and structures.
We should require that the information is provided as EFI configuration table:

It is strongly recommended that firmware provides an SMBIOS EFI configuration table with an SMBIOS 3.0 (64-bit) Entry Point and at least the following SMBIOS tables:

- BIOS Information (Type 0)
- System Information (Type 1)
- Baseboard (or Module) Information (Type 2)
- System Enclosure or Chassis (Type 3)
- Processor Information (Type 4)

2024-06-17 14:12 UTC, xypron commented on source/chapter2-uefi.rst
> +   provide SMBIOS tables and strutures and will explicitly list which ones are
%s/strutures/structures/

2024-06-18 08:33 UTC, vstehle commented
Dropping this pull request after [the call of June 17](https://github.com/ARM-software/ebbr/wiki/EBBR-Notes-2024.06.17); there is not enough remaining in the pull to be interesting.
Let's revive it later on.

2024-06-18 08:33 UTC, closed without merging